CREATE USER 'repl'@'192.168.0.12' IDENTIFIED BY 'Zaq1Zaq1';
GRANT REPLICATION SLAVE ON *.* TO 'repl'@'192.168.0.12';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS `blog`;
CREATE TABLE `blog` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'タイトル',
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='ブログ';
